/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./src/components/ActionCard.vue')['default']
    ListInput: typeof import('./src/components/ListInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestForTest: typeof import('./src/components/TestForTest.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
    TheView: typeof import('./src/components/TheView.vue')['default']
  }
}
